config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get '/login' => 'login#login', :as => :login
  get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
  get '/login/github', to: redirect('auth/github'), as: :github_login
  get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
  get '/auth/github/callback', to: 'login#github', as: :github_callback
  get '/logout' => 'login#logout', :as => :logout
  get '/user/profile', to: 'user#profile', as: :user_profile

  root to: 'map#index', as: 'root'
  get '/state/:state_symbol' => 'map#state', :as => :state_map
  get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

  get '/ajax/state/:state_symbol' => 'ajax#counties'

  # Routes for Events
  resources :events, only: %i[index show]
  get '/my_events/new' => 'my_events#new', :as => :new_my_event
  match '/my_events/new', to: 'my_events#create', via: [:post]
  get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
  match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
  match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

  # Routes for Representatives
  resources :representatives, only: [:index]
  resources :representatives do
      resources :news_items, only: %i[index show]
      get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
          :as                                                    => :new_my_news_item
      match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                    via: [:post]
      get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
          :as                                                    => :edit_my_news_item
      match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                    via: %i[put patch]
      match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                    via: [:delete]
      # Added this in to show the profile page of representative
      # TODO
      #get '/representatives/:representatives_id/show' => 'representatives#show',
      #    :as                                                    => :show_representative
  end
  get '/search/(:address)' => 'search#search', :as => 'search_representatives'

  #routes for campaign
  get '/campaign_finance' => 'campaign_finance#index'
  get '/campaign_finance/search' => 'campaign_finance/search'
end

app/models/representative.rb
# frozen_string_literal: true

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all

  # can do characterization tests in the fetures folder, can do cucumber tests file is .feature
  def self.civic_api_to_representative_params(rep_info)
    reps = []
    rep_info.officials.each_with_index do |official, index|
      rep = asign_address(rep_info, official, index)
      reps.push(rep)
    end
    reps
  end

  def self.asign_address(rep_info, official, index)
    street = 'N/A'
    city = 'N/A'
    zip = 'N/A'
    state = 'N/A'
    photo_u = ''

    title_temp, ocdid_temp = get_office(rep_info, index)

    unless official.address.nil?
      street = official.address[0].line1
      city = official.address[0].city
      zip = official.address[0].zip
      state = official.address[0].state
    end

    photo_u = official.photo_url unless official.photo_url.nil?

    Representative.find_or_create_by!({ name: official.name, ocdid: ocdid_temp, title: title_temp, street: street,
city: city, state: state, zip: zip, party: official.party, photo: photo_u })
  end

  def self.get_office(rep_info, index)
    rep_info.offices.each do |office|
      next unless office.official_indices.include? index

      title_temp = office.name
      ocdid_temp = office.division_id
      return title_temp, ocdid_temp
    end
  end
end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def index
    @representatives = Representative.all
  end

  # Added this in to show profile page of representative
  # TODO
  def show
    @representative = Representative.find_by(id: params[:id])
    if @representative.nil?
      redirect_to representatives_path, alert: 'no one found'
    else
      render :show
    end
  end
end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
end

app/views/representatives/index.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for a Representative

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_representatives_path, method: :get do
            .form-group.row
                .col-md-4
                    %label.col-form-label
                        Enter a location:
                .col-md-6
                    = text_field_tag(:address, nil, class: 'form-control')

            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
    .row
        .col-md-8.offset-md-2
            .table-responsive-md.pt-5
                %table.table.table-striped.table-hover#events
                    %caption Table of Representatives
                    %thead.thead-dark
                        %tr
                        %td
                            = link_to 'Finance', campaign_finance_path, class: 'btn btn-info'
                        %tr
                            %th Name
                            %th Office
                            %th Links
                    %tbody
                        - @representatives.each_with_index do |rep, _index|
                            %tr
                                %td= rep.name
                                %td= rep.title
                                %td
                                    = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                                        %i.fas.fa-newspaper
                                        News Articles
                                    = link_to 'Profile', representative_path(rep), class: 'btn btn-info'

app/views/representatives/show.html.erb
<h1>Representative Details</h1>

<p><strong>Name:</strong> <%= @representative.name %></p>
<p><strong>OCID:</strong> <%= @representative.ocdid %></p>
<p><strong>Title:</strong> <%= @representative.title %></p>
<p><strong>Street:</strong> <%= @representative.street %></p>
<p><strong>City:</strong> <%= @representative.city %></p>
<p><strong>State:</strong> <%= @representative.state %></p>
<p><strong>Zip:</strong> <%= @representative.zip %></p>
<p><strong>Party:</strong> <%= @representative.party %></p>
<%= image_tag @representative.photo %>